### ISSUE TITLE
[  ERROR ] Connectivity Lost With Proxy Server

### ISSUE THREAD

**Issue by fin1te** [pv03158/FastPeopleSearch---Scrapper#2]
Not working as of 11 Jan 2021. Let me know when it's up. Thanks and have a nice day Dev!

**Comment by prvarshney** [comment]
Actually that's not an error. You need to set proxy server settings in config file. If your country's IP is unblocked, you can also run this scrapper without any proxy server.

**Comment by fin1te** [comment]
how do i do that?

**Comment by fin1te** [comment]
> how do i do that?

I'm kinda new, so pass it if it's kinda dumb question to ask.

**Comment by prvarshney** [comment]
Read the config file, its self explainatory. I comment down everything there.
